global:
  operatorNamespace: operators
  instanceNamespace: instances
  imagePullPrefix: icr.io
  imagePullSecret: ibm-entitlement-key
  licenseAccept: true
  tetheredNamespaces: []
cpfs:
  imageRegistryNamespaceOperator: cpopen
  imageRegistryNamespaceOperand: cpopen/cpfs
  allowSubsetProjection: false
  configmapName: namespace-scope
  labels:
